spring.application.name=bulletin-board-service
server.port=8085

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/bulletindb}

management.endpoints.web.exposure.include=health,info
