apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      derivedFields:
        - datasourceUid: Loki
          matcherRegex: "request_id\":\"(\\w+)"
          name: CorrelationID
          url: "$${__value.raw}"

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
